### ISSUE TITLE
Feature Request: Comma separation

### ISSUE THREAD

**Issue by trainboy2019** [ev1l0rd/pedro-discordjs-bot#7]
## Feature Request

Pedro is primarily designed to work on the freeShop discord. As a result, any feature suggestions will be judged on their usefulness for the freeShop server and must be in accordance with the freeShop rules. If your feature request violates freeShop rules, it will not be accepted.

- [✔️ ] I agree to the previous paragraph.

Now you can make your feature request below: 
_________________________________

Hello, would it be possible to separate numbers by comma? like instead of 10541, it is 10,541? It makes numbers easier to read.

**Comment by noirscape** [comment]
I am assuming you mean for the xdicey command?

This stack answer should help me implement it I think: https://stackoverflow.com/a/3753507/4666756

Also, you just need to type an x in the checkbox. No need to use the checkbox emote :) .

**Comment by trainboy2019** [comment]
Yeah, and I had a feeling that dicey wasn't the only command to use numbers in the future. I already had the emoji window open when typing XD

**Comment by noirscape** [comment]
Closed in df76cad6d9c0eff143b20543931097eab5f37a67
